const GET_BEERS = 'GET_BEERS';
const GET_RENDER = 'GET_RENDER';
const LAZY_SCROLL = 'LAZY_SCROLL';
const DELETE_FROM_RENDER = 'DELETE_FROM_RENDER';
const ADD_TO_RENDER = 'ADD_TO_RENDER';
const ON_SELECT = 'ON_SELECT';

export default { GET_BEERS, GET_RENDER, LAZY_SCROLL, DELETE_FROM_RENDER, ADD_TO_RENDER, ON_SELECT };